[package]
name = "plugin-post-processing"
version = "0.1.0"
edition = "2021"

[dependencies]
alumet = { path = "../alumet" } # LOCAL + NO VERSION
anyhow = "1.0"
log = "0.4"
serde = { version = "1.0.210", features = ["derive"] }

[lints]
workspace = true
